#!/bin/sh

mem_status()
{
  . $HOME/.bash_colors

  mem_free=$(grep MemFree /proc/meminfo | awk '{print $2}')
  mem_buffers=$(grep Buffers /proc/meminfo | awk '{print $2}')
  mem_cached=$(grep "^Cached" /proc/meminfo | awk '{print $2}')
  mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')

  mem_free_percentage=`echo "scale=0; (($mem_buffers+$mem_cached+$mem_free)*100)/$mem_total" | bc -l`

  ESC="\033"
  RESET="$ESC[${DULL};${FG_WHITE};${BG_NULL}m"
  YELLOW="$ESC[${DULL};${FG_YELLOW}m"
  BRIGHT_GREEN="$ESC[${BRIGHT};${FG_GREEN}m"

  if [ $mem_free_percentage -gt 75 ]; then
    MEM="[${BRIGHT_GREEN}|${YELLOW}||||${RESET}]"
  elif [ $mem_free_percentage -gt 50 ]; then
    MEM="[${BRIGHT_GREEN}||${YELLOW}|||${RESET}]"
  elif [ $mem_free_percentage -gt 25 ]; then
    MEM="[${BRIGHT_GREEN}|||${YELLOW}||${RESET}]"
  elif [ $mem_free_percentage -le 25 ]; then
    echo -e "[${BRIGHT_GREEN}|||${YELLOW}|${RESET}]"
  fi

  /bin/echo -e "$MEM"
}

mem_status
